### ISSUE TITLE
Problem in information window

### ISSUE THREAD

**Issue by alessiobertolani** [cyberhobo/wordpress-geo-mashup#853]
Hi, I'm having this problem when I create the page with the global map. The content is not displayed on the popup. What can it depend on?

![list_–_OmA_test_e_Posta_in_arrivo_•_alessio_bertolani_fondazionecrfirenze_it](https://user-images.githubusercontent.com/60743817/73943151-8e00f600-48f0-11ea-93e5-9c3a1200f58f.png)

**Comment by cyberhobo** [comment]
The ajax request is being blocked by something. Often this happens when a site administrator unwittingly blocks requests to everything `/wp-admin`, not realizing that front end ajax requests need access to `/wp-admin/admin-ajax.php`. It could be any number of other things too: a plugin, server-level security rules, firewall, etc.
